version: '3.8'
services:
    php-apache-environment:
        image: web-sqli
        hostname: defender
        depends_on:
            - db
        ports:
            - "80"
            - "22"
        networks:
            - attack-defend
    attacker: 
        image: "attacker"
        hostname: attacker
        depends_on:
            - db
        tty: true
        networks:
            - attack-defend
    db:
        image: mysql-low
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "sqli"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "password"
        ulimits:
            nproc: 65535
            nofile:
                soft: 20000
                hard: 40000
        ports:
            - "3306"
        networks:
            - attack-defend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "80"
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
        networks:
            - attack-defend
networks:
    attack-defend:
        driver: bridge


